apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-site
  namespace: portfolio
spec:
  dnsNames:
    - www.bruzco.com
    - bruzco.com
  secretName: portfolio-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
