apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: angular-site
  namespace: football-prod
spec:
  dnsNames:
    - www.bruzcofantasy.com
    - bruzcofantasy.com
  secretName: bruzcofantasy-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
