apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deploy
  labels:
    app: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: jackbruzan/portfolio:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "400m"
            limits:
              memory: "600Mi"
              cpu: "600m"
      imagePullSecrets:
        - name: dockercreds
