---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "*.bruzco.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: portfolio-service
                port:
                  number: 4300
