apiVersion: v1
kind: Service
metadata:
  name: angular-site-internal-service
spec:
  selector:
    app: angular-site
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      name: http
